Feat/mock/leeyc
POSTCO2024/postcoil-frontend pull request #104
Opened 2024-09-07 17:25 UTC by dudco0040

## 🔖 Pull Request
####  Issue Number
- 103
####  branch
- feat/mock/leeyc

## 📋 개요

#### 변경 사항

- 작업 대상재 리스트 조회 화면 API 1차 연결 완료
- 각 공정 별로 작업 대상재 목록을 조회 할 수 있는 기능을 구현 
#### 관련 이슈 또는 문서

- #103 
- #67 

#### 특별히 봐줬으면 하는 부분
 
- 다른 기능 브랜치에 작성했는데, 옮기려다가 꼬일까봐 그냥 작업한 브랜치로 우선 PR 할게요! 😢 
- ✔️  작업한 내용은 이슈 (#103 )이고, 다음 작업부터는 올바른 브랜치에 작업하도록 하겠습니다. 해당 브랜치는 삭제해도 될 것 같아요 :) 

#### 테스트 가이드 및 기타 

 
 
- api url : http://localhost:8086/control/fc001a/list/${processCode}

## 🚀 PR 유형
어떤 변경 사항이 있나요?

- [x] ✨ 새로운 기능 추가
- [ ] 🐛 버그 수정
- [ ] 🎨 CSS 등 사용자 UI 디자인 변경
- [ ] 🔧 코드에 영향을 주지 않는 변경사항 (오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] ♻️ 코드 리팩토링
- [ ] 📝 주석 추가 및 수정
- [ ] 📚 문서 수정
- [ ] ✅ 테스트 추가, 테스트 리팩토링
- [ ] 🛠️ 빌드 부분 혹은 패키지 매니저 수정
- [ ] 📂 파일 혹은 폴더명 수정
- [ ] 🗑️ 파일 혹은 폴더 삭제

## 📸 스크린샷

### ScreenShot

## 👥 리뷰어
리뷰어를 태그해주세요.

- @dudco0040 
- @sohyun-ahn 

## ✅ PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항과 관련 문서를 모두 업데이트 했습니다.
- [x] 모든 종속 변경사항이 병합되었습니다.
- [x] 코드 리뷰어를 지정했습니다.

2024-09-07 17:48 UTC, sohyun-ahn requested changes

2024-09-07 17:48 UTC, sohyun-ahn commented on apps/control/src/pages/fc003/stock/StockCharts.tsx
이 파일은 fc003이라서 잘못 바꾼 거 같은데 맞다면 원래 코드로 돌려주실 수 있을까요?

2024-09-08 08:25 UTC, dudco0040 commented on apps/control/src/pages/fc003/stock/StockCharts.tsx
이 부분 예전에 작업하던 브랜치라 뭐가 맞는지 모르겠어서ㅠ 우선 원래 코드로 돌려놓겠습니다! !

2024-09-08 08:25 UTC, dudco0040 commented on apps/control/src/pages/fc003/stock/StockCharts.tsx
수정해서 다시 push 했습니다 ~

2024-09-08 10:22 UTC, merged